<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Couldn't create screenshot]]>
    </line>
    <line>
      <![CDATA[Connection refused: connect]]>
    </line>
    <line>
      <![CDATA[Couldn't create screenshot]]>
    </line>
    <line>
      <![CDATA[Connection refused: connect]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="1105677" started-at="2015-06-10T06:14:44Z" finished-at="2015-06-10T06:33:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1105677" started-at="2015-06-10T06:14:44Z" finished-at="2015-06-10T06:33:10Z">
      <class name="tryrc.rc">
        <test-method status="PASS" signature="attachScreenshotListener(java.lang.String, java.lang.String, org.testng.ITestContext)[pri:0, instance:tryrc.rc@1f0733a]" name="attachScreenshotListener" is-config="true" duration-ms="14" started-at="2015-06-10T11:44:44Z" finished-at="2015-06-10T11:44:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4444]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@1191d29]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- attachScreenshotListener -->
        <test-method status="FAIL" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:tryrc.rc@1f0733a]" name="setUp" is-config="true" duration-ms="0" started-at="2015-06-10T11:44:44Z" finished-at="2015-06-10T11:44:44Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:107)
	at com.thoughtworks.selenium.SeleneseTestBase.setUp(SeleneseTestBase.java:136)
	at com.thoughtworks.selenium.SeleneseTestBase.setUp(SeleneseTestBase.java:105)
	at com.thoughtworks.selenium.SeleneseTestNgHelper.setUp(SeleneseTestNgHelper.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:521)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.TestRunner.beforeRun(TestRunner.java:645)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[Couldn't create screenshot]]>
            </line>
            <line>
              <![CDATA[Connection refused: connect]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="getSelenium(boolean)[pri:0, instance:tryrc.rc@1f0733a]" name="getSelenium" is-config="true" duration-ms="0" started-at="2015-06-10T12:03:08Z" finished-at="2015-06-10T12:03:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSelenium -->
        <test-method status="SKIP" signature="setTestContext(java.lang.reflect.Method)[pri:0, instance:tryrc.rc@1f0733a]" name="setTestContext" is-config="true" duration-ms="0" started-at="2015-06-10T12:03:08Z" finished-at="2015-06-10T12:03:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTestContext -->
        <test-method status="SKIP" signature="rc()[pri:0, instance:tryrc.rc@1f0733a]" name="rc" duration-ms="1" started-at="2015-06-10T12:03:08Z" finished-at="2015-06-10T12:03:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rc -->
        <test-method status="SKIP" signature="checkForVerificationErrors()[pri:0, instance:tryrc.rc@1f0733a]" name="checkForVerificationErrors" is-config="true" duration-ms="0" started-at="2015-06-10T12:03:08Z" finished-at="2015-06-10T12:03:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkForVerificationErrors -->
        <test-method status="FAIL" signature="selectDefaultWindow()[pri:0, instance:tryrc.rc@1f0733a]" name="selectDefaultWindow" is-config="true" duration-ms="0" started-at="2015-06-10T12:03:08Z" finished-at="2015-06-10T12:03:08Z">
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: Connection refused: connect
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:120)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:100)
	at com.thoughtworks.selenium.DefaultSelenium.selectWindow(DefaultSelenium.java:380)
	at com.thoughtworks.selenium.SeleneseTestNgHelper.selectDefaultWindow(SeleneseTestNgHelper.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:521)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:736)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at com.thoughtworks.selenium.HttpCommandProcessor.getOutputStreamWriter(HttpCommandProcessor.java:148)
	at com.thoughtworks.selenium.HttpCommandProcessor.getCommandResponseAsString(HttpCommandProcessor.java:175)
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:117)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
            <line>
              <![CDATA[Couldn't create screenshot]]>
            </line>
            <line>
              <![CDATA[Connection refused: connect]]>
            </line>
          </reporter-output>
        </test-method> <!-- selectDefaultWindow -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tryrc.rc@1f0733a]" name="tearDown" is-config="true" duration-ms="0" started-at="2015-06-10T12:03:10Z" finished-at="2015-06-10T12:03:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tryrc.rc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
